version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/web
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    db:
        image: postgres:latest
        ports:
            - "5432:5432"