"""empty message

Revision ID: 502ca34a2402
Revises: 11a2f6102afb
Create Date: 2019-05-10 12:05:38.987620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502ca34a2402'
down_revision = '11a2f6102afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_trails', sa.Column('trail_id', sa.Integer(), nullable=True))
    op.drop_column('saved_trails', 'trail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_trails', sa.Column('trail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('saved_trails', 'trail_id')
    # ### end Alembic commands ###
